#!/usr/bin/env python
import argparse, subprocess, json, os, sys, base64, binascii, time, hashlib, re, copy, textwrap, logging, errno, shutil
try:
    from urllib.request import urlopen # Python 3
except ImportError:
    from urllib2 import urlopen # Python 2

def get_options_from_json(conf_json_s,ac,csr,acmd,crtf,chnf,ca):
    keys = ['AccountKey','CSR','AcmeDir','CertFile','ChainFile','CA']
    pvalue= [ac,csr,acmd,crtf,chnf,ca]
    value = []
    for i, key in enumerate(keys, start=0):
        if not pvalue[i]:
            if key in conf_json:
                if(conf_json[key]):
                    value.append(conf_json[key])
                else: value.append(None)
            else: value.append(None)
        else: value.append(pvalue[i])
    return value[0],value[1],value[2],value[3],value[4],value[5]
    
print get_options_from_json('{"ChainFile":"bad","CertFile":"CertFile"}',"g","a","fsd",None,None,"fsd")
